### ISSUE TITLE
[Bug Report] Failed to execute script download_manager

### ISSUE THREAD

**Issue by MagosCawl** [dr-nyt/NovelScraper#23]
- Operating System [OS]: Windows 10 version 19.09
 - App Version: 0.9.5
![error](https://user-images.githubusercontent.com/61636297/75615605-2d0ebb80-5b46-11ea-82a2-9a34456de8a8.PNG)

**Describe the bug**
I installed version 0.9.5 after using 0.9.4 without issues. Immediately upon trying to to download one of the items, added in 0.9.4, from the list (boxnovel), I received the error message "_Fatal error detected - Failed to execute script download_manager".

I tested uninstalling and installing the application (and manually checked that all contents except library.json was removed) without luck. Rebooted system as well, but no change.

I then tested adding new items both from boxnovel and novelplanet, but ran into same issue there.

**To Reproduce**
Unsure if this can be reproduced on other systems, but I just installed the application and immediately ran into the error.

**Expected behavior**
For the download_manager to start doing its thing.

**Screenshots**
Please see attached.

**Comment by dr-nyt** [comment]
I would look into this more when I get home, but for now, you could try disabling your anti-virus and see if that works.

**Comment by dr-nyt** [comment]
Never mind what I said earlier, I made a mistake in the code... I'll have to upload an update. Thanks for bringing this up 🍡

**Comment by dr-nyt** [comment]
Ok so I just fixed, but I'll have to do the new update when I get home.
You can fix it now if you do the following:
- Right-click on the NovelScraper icon on the desktop and select "open file location" (or just goto install location on your drive.)
- Inside the assets folder, open the module folder.
- Delete download_manager.exe already present.
- Paste this new download_manager.exe in there.
https://drive.google.com/file/d/1RH_4oqAl0JGAUqO1u6C2ygfAoVm2VuId/view?usp=sharing

**Comment by MagosCawl** [comment]
Hi! Many thanks for the swift response and resolution. That solved the issue, so I'll go ahead and close the ticket.
