### ISSUE TITLE
[Bug Report] Unable to complete download of some titles

### ISSUE THREAD

**Issue by MagosCawl** [dr-nyt/NovelScraper#24]
**Please complete the following information):**
 - Operating System [OS]: Windows 10 version 19.09 (patched up to February 2020)
 - App Version: 0.9.5

**Describe the bug**
On downloading certain novels, the download will fail partway. I've so far only encountered this for stories on Boxnovel.com. Two examples are "Taming Master" & "Paradise of Demonic Gods". 

The issue has happened across version and reboots, making me think that there's something with those two novels in particular that causes the error message, particularly in light of other stories downloading without any problems.

A cursory examination of the contents from the source makes me suspect, as far as a layman's guess goes, that the error happens when the naming convention of the chapters changes online partway through. For example, in Taming Master, up to chapter 258, the names have the same format, with chapter 258 being called "Chapter 258", but next chapter is called "Chapter 259 - The Dragon of Abyss, Bookbbook (1)".

The timing of the error message appear to match roughly that place in the chapter list during the download process, although I'm not sure.

**To Reproduce**
1. Add https://boxnovel.com/novel/taming-master/ or https://boxnovel.com/novel/paradise-of-demonic-gods/ to the application
2. Click on 'Download'
3. Wait

**Expected behavior**
For the downloads to complete successfully

**Screenshots**
![Error](https://user-images.githubusercontent.com/61636297/75626915-dd72d300-5bcb-11ea-9273-7571488c9962.PNG)

**Comment by dr-nyt** [comment]
You are probably right, box novel formatting is pretty bad. Thank god I didnt release the new update yet and thanks for reporting this bug.

Secret tip, if you ever want to know what the app is doing behind the scenes or want to know the full detail of an error then press "ctrl+shift+i" this will open up a log box which shows whats happening in detail.

**Comment by dr-nyt** [comment]
You were a bit off, the problem was on chapter 276.
Follow the earlier steps to replace the download_manager.exe file
https://drive.google.com/file/d/1btXfXsFnFIHdjpVWsDg9F5xX3tzhLseq/view?usp=sharing

I haven't tested this but it should work. Its really late so gotta hit the bed but if this doesn't fix it then ill fix when I get time tomorrow.

**Comment by MagosCawl** [comment]
Thanks! I tested it and it worked on 'Taming Master'. I also manually checked the contents of the epub file and confirmed that all chapters are there and can be accessed.

However, 'Paradise of Demonic Gods' threw an error after reaching 100% (checked the console - very neat). The log only said "null" though. I also tested on "The World Online", a title that had previously yielded an error message, and it too failed after 100%.

For 'Paradise of Demonic Gods', Boxnovel contains a total of 1163 chapters. The epub file contains up to chapter 1148 and then appears to have skipped 1149-1150, and throwing an error message on 1151 ("Error loading chapter number 1151"). I also confirmed that chapter 1149 and above are available at BoxNovel.

The epub reader I'm using, Freda, displays the same error message on chapter 800 and above of "The World Online". 798-799 was missing too. Just to be sure, I confirmed here as well that chapter 798 and above are available at BoxNovel.

Just to check if there was an issue with Freda, I loaded the epubs into Calibre and ran into the same issue there.

Let me know if you want me to test anything else; it's the least I can do.

**Comment by dr-nyt** [comment]
Thank you, that helps alot! I will test this when I get time today.

**Comment by dr-nyt** [comment]
I think I've solved the issue and I'm trying to download to check if it works but it takes a lot of time ;3

**Comment by dr-nyt** [comment]
FINALLY DONE! The problem was that the chapter headers were missing on the website and the code didn't know what to do if that happens.
Here is your update download_manager and I'll releasing an update soon.
https://drive.google.com/file/d/1GP0yxP_EFUuiQImj56tAJx1sISp9dEz3/view?usp=sharing

**Comment by MagosCawl** [comment]
Thank you so much for your help. I'll go ahead and close the ticket.
