### ISSUE TITLE
[Bug Report] source novel-planet cant fetch any titles

### ISSUE THREAD

**Issue by Gweenteaneko** [dr-nyt/NovelScraper#26]
**Please complete the following information):**
 - Operating System [OS]: win10 ver.1703
 - App Version: 0.9.6

**Describe the bug**
upon using the the source novel planet and pasting the the links then find, it always shows invalid link. reinstalling shows the same result

**To Reproduce**
1. Go to source 'novel planet'
2. add some links 
https://novelplanet.com/Novel/I-Alone-Level-Up
https://novelplanet.com/Novel/Chrysalis
etc.
3. click 'find'

**Expected behavior**
always shows invalid link in all novelplanet's link

**Screenshots**
![xcxc](https://user-images.githubusercontent.com/64141065/79984861-9e8c2b80-845e-11ea-810b-428857494275.png)

**Comment by dr-nyt** [comment]
Novelplanet uses Cloudflare to block bots like this app from accessing it. I have a module that acts like a human and tries to bypass it, but occasionally Cloudflare makes changes to catch these bots. You will have to wait for a bit for the module to get updated and I'll upload a new version then.

**Comment by Gweenteaneko** [comment]
thnx for the info. ill wait then

**Comment by dr-nyt** [comment]
I'll keep this issue open for anybody else who comes with the same problem until its fixed.

**Comment by dr-nyt** [comment]
This is fixed in the new version.
