### ISSUE TITLE
Library is always empty

### ISSUE THREAD

**Issue by Gweenteaneko** [dr-nyt/NovelScraper#27]
**Please complete the following information):**
-Operating System [OS]: win10 ver.1703
-App Version: 0.9.6

**Describe the bug**
after using Novel-Scraper the library(closing it) and it content is always missing (a bug? or just mine?) 

also

**To Reproduce**

**Expected behavior**
i always download many novel titles not having the list will cause it having downloaded again or not sure if i have the novel already causing it not being downloaded

**Screenshots**

**Comment by dr-nyt** [comment]
Could you try two things:

- Go to the library page of the app and press `Ctrl + Shift + i`. A console should open. Let me know of any errors you can see.

- Right-click on the app icon on your desktop and select `open file location`. When the folder opens, find a file called `library.json`, open it, copy whatever is inside and paste it here.

**Comment by Gweenteaneko** [comment]
No Library found. Generating new Library!

mainController.js:39 Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\NovelScraper\library.json'

mainController.js:47 Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\NovelScraper\library.json'

**Comment by dr-nyt** [comment]
Something on your computer is stopping the app from accessing the library file. You could try:

- Right-click on the app icon and `Run as administrator`.

- Very often just restarting the computer can also fix these issues.

- Or I'm releasing a new version of the app today which will fix a lot of problems and this will probably not be an issue as well.

**Comment by Gweenteaneko** [comment]
run as admin is working tnx.

**Comment by Gweenteaneko** [comment]
are you releasing a new app? what time will it be?

**Comment by dr-nyt** [comment]
The new version is done, I'm working on this new feature which will make the app automatically update. Should be done by tonight. I'll close this issue since its fixed.
