### ISSUE TITLE
[Bug Report] PDF Chapters Not Converting Correctly

### ISSUE THREAD

**Issue by Zopyrion** [dr-nyt/NovelScraper#31]
**Please complete the following information):**
 - Operating System [OS]:  Windows 10
 - 32bit / 64bit: 64bit
 - App Version: 1.0.0

**Describe the bug**
Novelplanet allows PDF's as chapters which doesn't convert correctly when downloaded. It results in a PDF file embedded within the epub when viewed, or not at all when I put it on a kindle.

**To Reproduce**
1. Download [a novel where chapters are uploaded as a PDF.](https://novelplanet.com/Novel/Grimgal-of-Ashes-and-Illusion)
2. Open the epub and view the chapter in question.

**Expected behavior**
The pages should continue sequentially. Instead, the chapter becomes a single page, which may or may not show up depending on the viewer.

**Screenshots**
(All pages of this chapter is nested within a single page on the epub.)
![bugpng](https://user-images.githubusercontent.com/21994296/80682712-05c66300-8a91-11ea-879c-d3a95d8c030a.png)

**Comment by dr-nyt** [comment]
I had no idea there were pdf chapters. I'll look into it and get back to you.

**Comment by dr-nyt** [comment]
Since novelplanet has shutdown, this issue has become irrelevant so I will close it.
