### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by zaki322** [dr-nyt/NovelScraper#33]
**Enter an appropriate Title above**

**Please complete the following information):**
 - Operating System [OS]: 
 - 32bit / 64bit:
 - App Version:

**Describe the bug**

**To Reproduce**
3. Search for '....'
4. See error.

**Expected behavior**

**Screenshots**
If helpful, add screenshots to help explain your problem.

**Comment by dr-nyt** [comment]
You havent written anything about the bug.. Did you post this by mistake?

**Comment by zaki322** [comment]
Hello
why don't chapter novel  when downloading him   it  all  in the same  text  file   please  add all  chapter  alone

**Comment by dr-nyt** [comment]
Im sorry i dont understand what you said. Maybe try using google translate or ask a friend who can translate. What language do you speak?

**Comment by dr-nyt** [comment]
I will close this issue since its been stale for so long.
