### ISSUE TITLE
Transferring to mobile

### ISSUE THREAD

**Issue by Synalith** [dr-nyt/NovelScraper#35]
I download and read light novels to read them on my iPhone. But I'm stuck using your 8.2 version because when I use the newer ones parts of all the chapters are missing when I load it onto my iPhone saying there is a error and but its fine if I open it up on my PC. Is there something different about the way it downloads the epubs or there a way for me to fix this myself?

![2020_06_02_06_52_IMG_0364](https://user-images.githubusercontent.com/62772953/83512795-b95eb080-a49e-11ea-99f8-8b1362316fdb.PNG)

**Comment by dr-nyt** [comment]
On android I use an app called `Moon+ Reader` to read my novels. May I know which app you use to open the files and have you tried any other reader apps from the app store?

**Comment by Synalith** [comment]
> On android I use an app called `Moon+ Reader` to read my novels. May I know which app you use to open the files and have you tried any other reader apps from the app store?

I use ibooks on the iphone.

**Comment by dr-nyt** [comment]
Try another app and let me know how that goes.

**Comment by Synalith** [comment]
> Try another app and let me know how that goes.

yea that worked some apps mess up while others dont.
